### ISSUE TITLE
Main live scenario

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#100]
In case of main-live - when next segment generation is not possible, add emsg to last generated segment. The MPD validity expiration is set to the duration of the current segment or smaller. Only after the Representation(s) under loss resumes, a new S element is written with S@t matching the earliest presentation time of the newly generated Segment (IOP 4.2 section 4.11 Deployment scenarios).

**Comment by niteeshbhat** [comment]
The IOP guidelines and the respective implementations and usages are updated in the PR
https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/76

Once the PR is merged, this issue can be closed.

**Comment by eceozturk** [comment]
PR is merged, closing this issue
