### ISSUE TITLE
A/V bitrates

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#101]
Test vector support according to the given bitrate selection for video representations

**Comment by niteeshbhat** [comment]
Not yet clear on what to be implemented.
More guidelines expected in future specs.

**Comment by waqarz** [comment]
Change http://testassets.dashif.org/#default/faq (added in the last)

How can open source tools be used to create DASH-IF content?
Open Source encoders packaged with FFmpeg and MP4Box DASH encoder can be used to generate DASH (test) content that covers a wide range of DASH features. A few resources on the web that document how to use these tools is gathered in the following (status May 2017):

"DASH Support in MP4Box" : https://gpac.wp.imt.fr/mp4box/dash/
"Radiant Media Player: Working with MP4Box" : https://www.radiantmediaplayer.com/guides/working-with-mp4box.html
"MPEG-DASH Content Generation with MP4Box and x264" : https://bitmovin.com/mp4box-dash-content-generation-x264/

The content generation, specifically audio/video bitrate selection can be guided using the instructions [here](https://docs.google.com/spreadsheets/d/1G6_Fn253dT8RezUiJkmPsA0oQT7-UDOcXuu7SLinXJw/edit?usp=sharing).

**Comment by waqarz** [comment]
Implemented in https://github.com/Dash-Industry-Forum/Test-Assets-UI-public/pull/4
