### ISSUE TITLE
Check for leap seconds-aware UTC timeline (live)

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#103]

**Comment by niteeshbhat** [comment]
From IOP 4.2, it is not clear what is this issue and what is expected from test assets.
May be more guidelines expected from future specs.

**Comment by waqarz** [comment]
IOP v4.2 Section 4.7.2. "The MPD time does not track leap seconds. If these occur during a live service they may advance or retard the media against the real time."

There seems nothing to be implemented on this.
