### ISSUE TITLE
Review clarification on permitted updates in the MPD

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#107]
- Check test vectors, 
- MPD@availabilityStartTime and Period@start shall not be changed over MPD updates

**Comment by niteeshbhat** [comment]
Implement in dynamic service validator

**Comment by niteeshbhat** [comment]
Implemented here : https://github.com/Dash-Industry-Forum/DynamicServiceValidator/pull/3
