### ISSUE TITLE
Transition from live to on-demand

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#108]
Clause 4.6.4 - For the case : DASH clients should support the transition from dynamic to static in the case when the @minimumUpdatePeriod is no longer present in the MPD.

**Comment by niteeshbhat** [comment]
It is discussed that  the current live emulator doesn't support the time limited content. So converting the time unlimited live content into on-demand is currently not possible.

**Comment by waqarz** [comment]
Cannot be done in live emulator by design: there is no notion of a time-limited service
