### ISSUE TITLE
Test content for different videos in one MPD

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#109]
Provide test content for different videos in one MPD using Tears of Steal (2 versions) including labels.

**Comment by niteeshbhat** [comment]
The test vector is https://dash.akamaized.net/dash264/TestCasesIOP41/MultiTrack/alternative_content/5/manifest_alternative_ToS_Viewpoint.mpd

provided under the testcase of alternate content offering 
https://testassets.dashif.org/#testcase/details/5a1c4c8f7cccbb15567e5682

**Comment by waqarz** [comment]
This is not the correct alternate video, @eceozturk please use this: https://www.youtube.com/watch?v=NcMqX8F43F8

**Comment by eceozturk** [comment]
- I am not sure where the above provided testvector is tested as the hev1 coded is not supported in dash.js.
- @waqarz , Is there any download link available for the new content? I could not find it.

**Comment by waqarz** [comment]
> * I am not sure where the above provided testvector is tested as the hev1 coded is not supported in dash.js.
> * @waqarz , Is there any download link available for the new content? I could not find it.

Its not a dash.js issue, Chrome does not support it. You can use MS Edge browser.

**Comment by eceozturk** [comment]
The provided source content for ToS could not be downloaded since the cleaned up version of the shooting could not be found.

Instead a 360 video is used ([source link](https://vimeo.com/215985972)) as the alternative content. Main content is generated from this 360 video by extracting 1080p-sized mid portion of the video frames.

The generated test vector can be found at:
https://testassets.dashif.org/#testvector/details/5d2c7e20a5eeda55aa663350
