### ISSUE TITLE
On-demand test vectors are missing indexRange

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/Test-Vectors#114]
DASH-IOP 3.2.1 requires that indexRange is present, but it's missing from some of the on-demand test vectors. For example:
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eaccac

When these are replaced, I'd suggest also including initialization ranges, since I think it's more in line with what providers are actually doing. I've opened an issue to look at whether we can make inclusion mandatory here:
https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/242

**Comment by eceozturk** [comment]
Thanks for reporting. There was also a bug in the conformance software regarding this check, which is now solved (See issue: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/391). The test vector's correction will be done accordingly.

**Comment by eceozturk** [comment]
This test vector and couple more with the same indexRange issue are updated. Another related issue was #46. 

http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eaccac
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd10
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd13
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd11
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd12

Closing this issue now.
