### ISSUE TITLE
Test Vectors Use Wrong Namespace

### ISSUE THREAD

**Issue by sannies** [Dash-Industry-Forum/Test-Vectors#12]
XML namespaces are case sensitive. 
http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd
defines `urn:mpeg:DASH:schema:MPD:2011`

all test vectors seem to use  `urn:mpeg:dash:schema:mpd:2011`

Is the ISO wrong or are the test vectors wrong?

**Comment by waqarz** [comment]
Test vectors are according to Amd. 1 of DASH spec. and hence current.
