### ISSUE TITLE
presentationTimeOffset missing from period #2 in http://dash.edgesuite.net/dash264/TestCases/5a/1/manifest.mpd

### ISSUE THREAD

**Issue by kirkshoop** [Dash-Industry-Forum/Test-Vectors#14]
@KozhinM "I found an issue the multi-period mpd http://dash.edgesuite.net/dash264/TestCases/5a/1/manifest.mpd. For the second period Perid@start = 188, but the media time of the first segment of the second period is about 0.089. No @presentationTimeOffset is provided. As a result we have currentTime = 188, buffer.buffered.start(0) = 0.089. Looks like @presentationTimeOffset must be set."

**Comment by waqarz** [comment]
This issue is still somehow left open. Those MPDs indeed had issues and have been pulled some time ago, latest content is here: http://dashif.org/testvectors/#MP
