### ISSUE TITLE
Trick mode

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Test-Vectors#16]
The current samples for trick mode
http://dash.edgesuite.net/dash264/TestCasesHD/1a/qualcomm/1/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/1a/qualcomm/2/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/1b/qualcomm/1/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/1b/qualcomm/2/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/1c/qualcomm/1/MultiRate.mpd

 do not seem to be compliant. Issues:
1. The trick mode should reside in a separate adaptation set. Representations and Adaptation Sets should be explicitly signaled in order to distinguish them from regular playout and to avoid client confusion in the playout, for instance define a trick mode scheme to be used with the Essential Descriptor. We need to find out if MPEG defined such a signal and then use it, or else create one that is consistent with our recommendation. 
2. The @group attribute should be used to link the trick mode adaption set to its non-trick-mode sibling.
3. The representation should include the @maxPlayoutRate attribute

Cheers
Will

**Comment by waqarz** [comment]
The trick mode vectors have been updated, please check.

**Comment by waqarz** [comment]
Provided updated vectors. Client team still reporting issue with playing content with PTO.
