### ISSUE TITLE
D-Dash mpds have incorrect value of @mediaPresentationDuration and Period@duration

### ISSUE THREAD

**Issue by KozhinM** [Dash-Industry-Forum/Test-Vectors#17]
For all of the mpds listed below `@mediaPresentationDuration = Period@duration = PT1H26M = 5160sec`:
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=2&type=full
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=4&type=full
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=6&type=full
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=10&type=full
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=15&type=full

But the stream duration calculated as `segmentDuration * segmentsNumber` differs from the value of `@mediaPresentationDuraton`. For example,  in
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=6&type=full
I observe:
`segmentDuration * segmentsNumber = 6.006 * 874 = 5249.244sec (for video)`,  `5.952 * 882 = 5249.664sec (for audio)`.
Note: in the other ddash streams the calculated duration varies from about 5246 to 5255.

These mpds have SegmentList, so segmentNumber = number of all segments in the list.

**Comment by waqarz** [comment]
This track is for DASH-IF test vectors, how does this relate to them?

**Comment by waqarz** [comment]
Unrelated, closing.
