### ISSUE TITLE
[Standard Definition MPDs] [Single Resolution Multi-Rate] Test Vector 1 Violates 4.2.2 of DASH-264/AVC Test Cases and Test Vectors.

### ISSUE THREAD

**Issue by vladimir-kazakov** [Dash-Industry-Forum/Test-Vectors#21]
Hi!

I noticed that the mentioned vector (http://dash.edgesuite.net/dash264/TestCases/1a/netflix/exMPD_BIP_TC1.mpd) violates one requirement defined in 4.2.2 of DASH-264/AVC Test Cases and Test Vectors: the HE-AAC v2 (@codecs="mp4a.40.29") codec is expected to be used for the audio content, but in the MPD, the HE-AAC (@codecs="mp4a.40.5") is used.

I also noticed that the validator (http://dashif.org/conformance.html) doesn't report these violations, saying that MPD is correct.

**Comment by joywelt** [comment]
Fixed.
The conformance software need to be updated accordingly.

**Comment by waqarz** [comment]
codec "mp4a.40.5" is allowed in DASH-IF IOP
