### ISSUE TITLE
Link to reference player needs to be updated.

### ISSUE THREAD

**Issue by dsparacio** [Dash-Industry-Forum/Test-Vectors#25]
When you click the play button icon on the vectors page it links to the 1.0 version of the DASH IF reference player.  We are on version 1.3.  We should have a consistent location for the latest public release under a folder structure that does not change such as /current  -  So we do not have to update the links for all test vectors with each dash.js release.

**Comment by waqarz** [comment]
This would mean that we should have something like: http://dashif.org/reference/players/javascript/current/samples/dash-if-reference-player/index.html that has the latest player. So I gather first we need to set this up and then update the URLs?

**Comment by waqarz** [comment]
During the site update this has been fixed (probably from someone at Akamai?). Thanks.
