### ISSUE TITLE
TestCasesHEVC/2b/2/BBB_Live_HEVC_MultiRes.mpd has invalid initialization segments

### ISSUE THREAD

**Issue by sdroege** [Dash-Industry-Forum/Test-Vectors#27]
http://dash.edgesuite.net/dash264/TestCasesHEVC/2b/2/BBB_Live_HEVC_MultiRes.mpd

The problem with this stream is that the same initialization segment is used for all resolutions. The initialization segment contains the resolution in the stsd atom though, and this should be consistent with whatever resolution is inside the video bitstream. Additionally the initialization segment also contains the hvc codec data, which among other things contains the resolution and should also be consistent with the video bitstream.

The same seems to apply to the other HEVC multi resolution streams. The AVC/MPEG2 multi resolution streams handle this correctly.

**Comment by waqarz** [comment]
Updated content being synced.
