### ISSUE TITLE
High Definition MPDs – Single Resolution Multi-Rate – Test Vector 1/2 have wrong indexRange

### ISSUE THREAD

**Issue by sdroege** [Dash-Industry-Forum/Test-Vectors#30]
http://dash.edgesuite.net/dash264/TestCasesHD/1a/qualcomm/1/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/1a/qualcomm/2/MultiRate.mpd

The indexRange claims e.g. 820-2435 (second stream) for the audio. However in the actual media, the sidx atom is at 784-2399 (so off by 36 bytes). The same offset is needed for the indexRanges of the video media, and the first stream.

Other streams from the test vectors with similar usage of DASH features don't have this 36 byte offset, e.g. http://dash.edgesuite.net/dash264/TestCases/9a/qualcomm/1/MultiRate.mpd and http://dash.edgesuite.net/dash264/TestCases/9a/qualcomm/2/MultiRate.mpd

**Comment by sdroege** [comment]
Similar problems with other streams:

http://dash.edgesuite.net/dash264/TestCasesHD/2a/DTV/1/ondemand.mpd
audio sidx is at 678 inside the stream instead of 699 as given by the manifest

http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/1/MultiResMPEG2.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/1/ED_512_640K_MPEG2_video_init.mp4 says index range is 890-. While inside the file it actually is at 850.
http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/1/ED_MPEG2_32k_init.mp4 says index range 820-, inside the file it's at 780.

http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/2/MultiRes.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/2/BBB_HD_32k_init.mp4 manifest 820, actual stream 780. http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/2/BBB_512_640K_video_init.mp4 manifest 890, actual stream 850.

**Comment by waqarz** [comment]
Agreed, the conformance tool is not checking index ranges properly and hence does not report this. We are working in the conformance tool to fix this: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/88

**Comment by waqarz** [comment]
- Vectors fixed, there was a sync issue. Except:
- DTV vector has been pulled.
- Conformance implemented correctly for sidx: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/88
