### ISSUE TITLE
Missing / incorrect mime types for mpd

### ISSUE THREAD

**Issue by NickDrouin** [Dash-Industry-Forum/Test-Vectors#32]
The following do not set mime types correctly to application/dash+xml 

http://www.digitalprimates.net/dash/streams/gpac/mp4-main-multi-mpd-AV-NBS.mpd
http://www.digitalprimates.net/dash/streams/mp4-live-template/mp4-live-mpd-AV-BS.mpd 

http://html5.cablelabs.com:8100/cenc/ck/dash.mpd (and similar)

**Comment by waqarz** [comment]
Are any of these DASH-IF test vectors? For which test case are these?

**Comment by waqarz** [comment]
This issue seems unrelated to DASH-IF test vectors, this track is exclusively for issues noted in DASH-IF test vectors listed on http://dashif.org/test-vectors/ . Please reopen if this is incorrect.

**Comment by NickDrouin** [comment]
This is from the Dash Reference Client streams pull-down menu: Segment List; Segment Template; CableLabs Cenc ClearKey; CableLabs Cenc *
If these are not under Test-Vector purview, then indeed, this bug is misfiled and should be copied to the reference player project.
