### ISSUE TITLE
Content length mismatches on generated mpds

### ISSUE THREAD

**Issue by NickDrouin** [Dash-Industry-Forum/Test-Vectors#33]
These (and similar) have content length mismatches:
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=2&type=full
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=4&type=full
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=6&type=full

**Comment by waqarz** [comment]
Are any of these DASH-IF test vectors? For which test case are these?

**Comment by waqarz** [comment]
This issue seems unrelated to DASH-IF test vectors, this track is exclusively for issues noted in DASH-IF test vectors listed on http://dashif.org/test-vectors/ . Please reopen if this is incorrect.

**Comment by NickDrouin** [comment]
These are from the Dash Reference Client streams pull-down menu: D-Dash 1,2,3,4,5,6.
If these are not under Test-Vector purview, then indeed, this bug is mis-filed and should be copied to the reference player project.
