### ISSUE TITLE
404 on some mpdGenerator URLs

### ISSUE THREAD

**Issue by NickDrouin** [Dash-Industry-Forum/Test-Vectors#34]
This 404's
http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=8&type=full
With a custom error response regarding parameterization.

**Comment by waqarz** [comment]
This issue seems unrelated to DASH-IF test vectors, this track is exclusively for issues noted in DASH-IF test vectors listed on http://dashif.org/test-vectors/ . Please reopen if this is incorrect.

**Comment by NickDrouin** [comment]
This is from the Dash Reference Client streams pull-down menu: D-Dash 4
If these are not under Test-Vector purview, then indeed, this bug is misfiled and should be copied to the reference player project.
