### ISSUE TITLE
Trick Mode byte range streams not working

### ISSUE THREAD

**Issue by rashmimittal** [Dash-Industry-Forum/Test-Vectors#36]
When using this stream - http://dash.edgesuite.net/dash264/TestCases/9a/qualcomm/1/MultiRate.mpd, the sidx seems to have the correct duration for each sub-segment of approximately 2 secs, where it may have 2 frames in each sub-segment. When we download the subsegment and feed it to the MSE sourceBuffer the buffer range being detected is .08 seconds instead of 2 seconds for segments. We tried parsing the segment bytes and each subsegment seems to contain 2 samples (as expected) but the trun sample duration being returned is undefined. This seems to be causing the browser’s MSE implementation to also not detect the correct duration.

**Comment by waqarz** [comment]
I have checked this but cant find an issue with the vector. The samples in trun have sample duration present flag set to false; there is no default sample duration in tfhd, only in trex box there is the default sample duration 16,384 on a timescale of 16,384, so it should be 1 second sample duration.
