### ISSUE TITLE
Conformance issue with a test vector and it violates 3.2.4 of DASH-IF IOP

### ISSUE THREAD

**Issue by joywelt** [Dash-Industry-Forum/Test-Vectors#38]
For this test vector http://dash.edgesuite.net/dash264/TestCases/1a/netflix/exMPD_BIP_TC1_relative.mpd
the conformance software has the following warnings and errors: 

(Representation in Adaptation set 1)
major brand ('mp42') not also found in list of compatible brands
WARNING: CTTS atom has no entries so is un-needed
WARNING: CTTS atom has no entry with a non-zero offset so is un-needed
WARNING: unknown traf atom 'sdtp'
WARNING: unknown traf atom 'sdtp'
WARNING: unknown traf atom 'sdtp'
...
WARNING: unknown traf atom 'sdtp'
### Buffer underrun conformance error: first (and only one reported here) for sample 1 of run 1 of track fragment 1 of fragment 19 of track id 1 (sample absolute file offset 305863, fragment absolute file offset 305136, bandwidth: 64000)

(All representations in Adaptation set 2)
ImageDescription name must be ''
Warning: Unknown atom found "pasp": video sample descriptions would not normally contain this
WARNING: CTTS atom has no entries so is un-needed
WARNING: CTTS atom has no entry with a non-zero offset so is un-needed
WARNING: unknown traf atom 'sdtp'
WARNING: unknown traf atom 'sdtp'
WARNING: unknown traf atom 'sdtp'
...
WARNING: unknown traf atom 'sdtp'
### Buffer underrun conformance error: first (and only one reported here) for sample 45 of run 1 of track fragment 1 of fragment 15 of track id 2 (sample absolute file offset 1331944, fragment absolute file offset 1104334, bandwidth: 500000)

I checked the mpd and it violates some requirements defined in 3.2.4 of DASH-IF IOP.

These attributes and elements are missing:

Video content: @maxFrameRate (or @frameRate), @par, @sar.
Audio content: @audioSamplingRate, AudioChannelConfiguration.

**Comment by waqarz** [comment]
This vector is nowhere on the DASH-IF test vector page (http://dashif.org/test-vectors/)
