### ISSUE TITLE
broken link in Test vectors page

### ISSUE THREAD

**Issue by joywelt** [Dash-Industry-Forum/Test-Vectors#39]
In this page, this vector http://dash.edgesuite.net/dash264/TestCases/1b/qualcomm/1/MultiRate.mpd does not exist. 
It's under STANDARD DEFINITION -> Single Resolution Multi-Rate -> Test Vector 8

**Comment by waqarz** [comment]
Check if this folder exists locally, if the name of the MPD is different?

**Comment by waqarz** [comment]
@joywelt Website updated.
