### ISSUE TITLE
Conformance tool - add checking for period @Start attribute for dynamic manifests

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Test-Vectors#4]
Hi Will,

This tool was implemented back in the days when this was conforming :) also, we do not have a conformance too according to what you have described, that too is unfortunate. I have updated the static to dynamic tool and now these attributes will appear in the same URLs. Hope this fixes vectors assigned to me.

Can you please open an issue at: https://github.com/Dash-Industry-Forum/Test-Vectors/issues ,  may be copy paste this email. It would be good to have this no matter how minor the issues are, so that we can keep a track of what has been updated.

Best regards,
Waqar.

On Sat, Feb 8, 2014 at 1:50 AM, Law, Will wilaw@akamai.com wrote:
Hi Torbjorn and Waqar

Kirk is working on completing the 1.1 release of the dash.js player and we’d like it to be compliant with your live streams. The streams identified below do not specify the period @Start attribute and hence are not MPEG-DASH compliant. Is it possible to update them to add the @Start attribute? The intended value is most likely zero, however the player is not allowed to assume this and the attribute is required per section  5.3.2.1 of the DASH spec (see quote below).

Cheers

Will

The following mpd have only one period and the period does not specify the @Start attribute. Therefore the period does not match any definition of a ‘Regular Period’ and thus DashManifestExtensions.getRegularPeriods returns an empty array.
1. MobiTV

URL: http://54.201.151.65/livesim/testpic_2s/Manifest.mpd

Owner: Torbjorn Einarsson
1. DASH IF Test Vector #1

URL: http://dasher.eu5.org/statodyn.php?type=mpd&pt=1376172180&tsbd=120&origmpd=http%3A%2F%2Fdash.edgesuite.net%2Fdash264%2FTestCases%2F1b%2Fthomson-networks%2F2%2Fmanifest.mpd&php=http%3A%2F%2Fdasher.eu5.org%2Fstatodyn.php&mpd=&debug=0&hack=.mpd

Owner: Waqar
1. DASH IF Test Vector #2

URL: http://dasher.eu5.org/statodyn.php?type=mpd&pt=1376172390&tsbd=120&origmpd=http%3A%2F%2Fdash.edgesuite.net%2Fdash264%2FTestCases%2F2b%2Fthomson-networks%2F2%2Fmanifest.mpd&php=http%3A%2F%2Fdasher.eu5.org%2Fstatodyn.php&mpd=&debug=0&hack=.mpd

Owner: Waqar
1. DASH IF Test Vector #3

URL: http://dasher.eu5.org/statodyn.php?type=mpd&pt=1376172485&tsbd=10&origmpd=http%3A%2F%2Fdash.edgesuite.net%2Fdash264%2FTestCases%2F2b%2Fthomson-networks%2F1%2Fmanifest.mpd&php=http%3A%2F%2Fdasher.eu5.org%2Fstatodyn.php&mpd=&debug=0&hack=.mpd

Owner: Waqar

5.3.2   Period

5.3.2.1     Overview

A Media Presentation consists of one or more Periods. A Period is defined by a Period element in the MPD
element.

The type of the Period, either a regular Period or an Early Available Period, as well as the PeriodStart time of a regular Period is determined as follows:

  If the attribute @start is present in the Period, then the Period is a regular Period and the
PeriodStart is equal to the value of this attribute.

  If the @start attribute is absent, but the previous Period element contains a @duration attribute then then this new Period is also a regular Period. The start time of the new Period PeriodStart is the sum of the start time of the previous Period PeriodStart and the value of the attribute @duration of the previous Period.

  If (i) @start attribute is absent, and (ii) the Period element is the first in the MPD, and (iii) the
MPD@type is 'static', then the PeriodStart time shall be set to zero.

  If  (i)  @start attribute  is  absent,  and  (ii)  the  previous  Period element  does  not  contains  a
@duration attribute or the Period element is the first in the MPD, and (iii) the MPD@type is
'dynamic', then this Period is an Early Available Period (see below for details).

For any regular Period the following holds: PeriodStart reflects the actual time that should elapse after playing the media of all prior Periods in this Media Presentation relative to the PeriodStart time of the first Period in the Media Presentation. The Period extends until the PeriodStart of the next Period, or until the end of the Media Presentation in the case of the last Period. More specifically, the difference between the PeriodStart time of a Period and either the PeriodStart time of the following Period, if this is not the last Period, or the value of the MPD@mediaPresentationDuration if this is the last one, is the presentation duration in Media Presentation time of the media content represented by the Representations in this Period.

Early Available Periods may be used to advertise initialization of other non-media data before the media data itself is available. Period elements documenting early available Periods shall not occur before any Period element documenting a regular Period. For Early Available Periods, any resources that are announced in such a Period element shall be available. Such a Period element shall not contain URLs to Media Segments. The data contained in such a Period element does not represent a Period in the Media Presentation. Only when  the  PeriodStart  time  becomes known  through  an  update  of  the  MPD,  such  a  Period element represents  a  regular  Period.  However,  an  update  of  the  MPD  may  even  remove  a  Period element representing an Early Available Period in later updates of  the MPD as  long as no  PeriodStart time is associated with the Period.
associated with the Period.
## 

Dr. Waqar Zia || zia@nomor.de || phone +49 89 978980 27 || cell +49 176 24115006 ||

Nomor Research GmbH  -  Sitz der Gesellschaft: München - Registergericht: München, HRB 165856 – Umsatzsteuer-ID: DE238047637 - Geschäftsführer: Dr. Thomas Stockhammer, Dr. Ingo Viering.

**Comment by waqarz** [comment]
To my understanding, this has been resolved.
