### ISSUE TITLE
Multiple periods test vector issue

### ISSUE THREAD

**Issue by arnemo** [Dash-Industry-Forum/Test-Vectors#42]
I'm trying to play the test vectors for multiple periods but none of them seems to be working, i have tested a few test vectors of other categories and they work fine. Thanks in advance.

/Marcus

**Comment by arnemo** [comment]
The multiple period video sample stream from the drop down menu of the 1.5.0 reference client (http://dashif.org/reference/players/javascript/v1.5.0/samples/dash-if-reference-player/index.html) works. but the test vectors at http://dashif.org/test-vectors/#MP do not.

**Comment by joywelt** [comment]
@arnemo Please try to play the test vectors at http://dashif.org/test-vectors/#MP with http://dashif.org/reference/players/javascript/v2.0.0/samples/dash-if-reference-player/index.html.

**Comment by waqarz** [comment]
There seems to be no conformance issues with the vectors.
