### ISSUE TITLE
AVC3 HE-AAC sample is not HE-AAC

### ISSUE THREAD

**Issue by phloxic** [Dash-Industry-Forum/Test-Vectors#43]
http://dash.edgesuite.net/dash264/TestCases/5b/1/manifest.mpd claims to have mp4a.40.5 audio - HE-AAC - but it does not seem to:

```
$ MP4Client http://dash.edgesuite.net/dash264/TestCases/5b/1/manifest.mpd 2>&1 | grep Audio
[Codec] ODM2 ES4: Cannot find decoder for stream type MPEG-4 Audio AAC LC
```

With a HE-AAC track I get:

```
$ MP4Client http://media.blacktrash.org/ccc.mpd 2>&1 | grep Audio
[Codec] ODM1 ES2: Cannot find decoder for stream type MPEG-4 Audio SBR
```

which I know is true.

Further indication: the sample stream plays on Android, the other does not.

(migrated from https://github.com/Dash-Industry-Forum/dash.js/issues/1259)

**Comment by AdithyanIlangovan** [comment]
Thanks for raising the issue.

This observation was cross-verified locally using the ffprobe command.
- Ideally, for this stream http://dash.edgesuite.net/dash264/TestCases/5b/1/manifest.mpd, 
  the ffprobe command should result in codec being displayed as: **Audio: aac (HE-AAC)(mp4a)**.
- For example, this stream http://dash.edgesuite.net/dash264/TestCasesMCA/fraunhofer/HE-AACv2_Multichannel/1/6chID/6chId_480p_single_adapt_heaac5_1_sidx.mpd, results in codec begin displayed as earlier
- But, currently for the stream it is being shown as : **Audio: aac (mp4a)** 

Possible fixes:
- Rename the .mpd for the appropriate audio format.

Still not completely fixed.

**Comment by AdithyanIlangovan** [comment]
Renamed mp4a.40.5 to mp4a.40.2 (corresponds to AAC) in the manifest file.
Issue fixed locally. Yet to be synced to the main server.
The correct version could be online soon.

**Comment by AdithyanIlangovan** [comment]
This particular test vector is no longer found in the main dashif.org website. 
The support for this test vector will be depreciated from now.
