### ISSUE TITLE
Provide subtitle (application/ttml+xml) vectors with more than one segment

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/Test-Vectors#44]
There are four test vectors with TTML subtitles (mimeType="application/ttml+xml"), however in all four cases there's only a single segment of TTML. Please could a sample containing multiple segments of TTML be added? This would help to clarify whether begin/end timestamps in each segment of TTML are absolute or relative to the start of the segment, and would make it easier to check that players implement which ever one of these is correct (I'm not actually sure which is correct).

Ditto for WebVTT should any WebVTT samples be added in the future.

**Comment by AquilesCanta** [comment]
Ping

**Comment by waqarz** [comment]
Is any of your companies DASH-IF members? The easiest way would be to raise this issue in an IOP call.

**Comment by joywelt** [comment]
@ojw28 Do you mean adaptation set by "segment" ? There is an example http://dash.edgesuite.net/dash264/TestCases/4b/qualcomm/2/TearsOfSteel_onDem5secSegSubTitles.mpd
which has two adaptation sets with TTML subtiles.

**Comment by ojw28** [comment]
@joywelt - No, I mean segment by segment. If you have a three hour long movie you may want to deliver the subtitles in segments (e.g. 60 seconds long each) rather than delivering the whole thing as a single segment. This is also relevant for live streams, where you have no choice but to segment subtitles into short duration files.

**Comment by sandersaares** [comment]
DASH-IF IOP v3.3 section 6.4.5 forbids the use of multiple plaintext text segments, so I suggest this issue be closed as "by design".

**Comment by ojw28** [comment]
Interesting. That section does indeed appear to disallow this case, thanks for point it out! Having said that, what does "proper timing" even mean in the following sentence from that section. I think it's equally easy to represent the same range of timestamps in non-packaged and ISOBMFF-packaged, so it seems pretty odd to restrict to a single segment for this reason:

> If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or
> 8 WebVTT segments are expected be used to provide proper timing.

**Comment by sandersaares** [comment]
I have heard from others in DASH-IF that this topic went through quite a few rounds of discussion (that I was not part of) and the overall impression I got was that the DASH-IF viewpoint is that everyone should use ISOBMFF for text segments and allowing plaintext files is a "if you really must" type of situation, intentionally constrained and minimized just to let in some backward compatibiltiy.

The upcoming MPEG CMAF will likely emphasize this even more (as the concept of "things not in ISOBMFF" is entirely alien to CMAF).

**Comment by ojw28** [comment]
I think it would be good for the IOP doc to be updated so as to not imply "proper" timing is possible with ISOBMFF-packaging but not without. Unless this is actually true, in which case an explanation of what this means would be helpful. I'll file a bug on the document suggesting this.

That nit-pick aside, I've no objection to the viewpoint you mention. It does feel preferable to use ISOBMFF if only from a consistency point of view w.r.t the audio and video streams. Thanks for the info, and closing as suggested.
