### ISSUE TITLE
A mpd does not provide neither @indexRange nor RepresentationIndex should not be used for test vector

### ISSUE THREAD

**Issue by hyunkim9123** [Dash-Industry-Forum/Test-Vectors#46]
A mpd does not provide neither @indexRange nor RepresentationIndex should not be used for test vector.
Please consider to remove http://dash.edgesuite.net/dash264/TestCasesMCA/dolby/1/1/ChID_voices_51_256_ddp.mpd . 
The discussion of this mpd has been done at  [https://github.com/Dash-Industry-Forum/dash.js/issues/1517](https://github.com/Dash-Industry-Forum/dash.js/issues/1517)

**Comment by eceozturk** [comment]
This test vector and couple more with the same indexRange issue are updated. 

http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eaccac
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd10
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd13
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd11
http://testassets.dashif.org/#testvector/details/586fb3879ae9045678eacd12

Closing this issue now.
