### ISSUE TITLE
Vectors still pointing to HTTP on Akamai?

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Test-Vectors#47]

**Comment by wilaw** [comment]
Info note: Any vector accessed via dash.edgesuite.net/... can only be access via http.
If you wish to request over https (with a valid cert) or over http, then the host name should be changed to dash.akamaized.net/

**Comment by waqarz** [comment]
Vectors still need fixing of server URL:

	http://dash.edgesuite.net/dash264/TestCasesIOP33/adapatationSetSwitching/3/manifest.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/adapatationSetSwitching/4/manifest.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/adapatationSetSwitching/1/manifest.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/resolveToZero/1/manifest.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/multiplePeriods/1/manifest_multiple_Periods_Add_Remove_Representation.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/multiplePeriods/2/manifest_multiple_Periods_Add_Remove_AdaptationSet.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/multiplePeriods/3/manifest_multiple_Periods_Content_Offering_CDN.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/multiplePeriods/4/manifest_multiple_Periods_Different_SegmentDuration.mpd
	http://dash.edgesuite.net/dash264/TestCasesIOP33/adapatationSetSwitching/2/manifest.mpd
	
	
Fixed: 	
	
	http://dash.edgesuite.net/dash264/TestCases/9b/qualcomm/3/Trick_Multi_live.mpd
	http://dash.edgesuite.net/dash264/TestCases/9a/qualcomm/3/Trick_Multi.mpd
	http://dash.edgesuite.net/dash264/TestCases/9b/qualcomm/4/Trick_Single_live.mpd
	http://dash.edgesuite.net/dash264/TestCases/9a/qualcomm/4/Trick_Single_Thumb.mpd

**Comment by niteeshbhat** [comment]
Updated all the vectors in dash test assets (http://testassets.dashif.org/#testvector/list)., all pointing now to http://dash.akamaized.net...
