### ISSUE TITLE
Set cache control headers on time sync URL

### ISSUE THREAD

**Issue by TheModMaker** [Dash-Industry-Forum/Test-Vectors#53]
Several of the live test assets use `http://vm2.dashif.org/dash/time.txt` for determining clock sync.  The clients should send a HEAD request to get the `Date` header from the response.  Unfortunately the response does not include cache control headers, meaning the response may be cached.  Firefox will cache the entire HEAD response, not sending it at all.

The minimum would be to set `Cache-control: no-cache` to ensure the HEAD is at least sent again.  Setting `Cache-control: no-cache, no-store` would mean it cannot be cached at all.

**Comment by waqarz** [comment]
@TheModMaker can you please report it here: https://github.com/Dash-Industry-Forum/dash-live-source-simulator/issues , this can be tracked better there since it seems to be related to the implementation of the emulator. I will close it from Test Vectors.

**Comment by TheModMaker** [comment]
Ok, Dash-Industry-Forum/dash-live-source-simulator#45.

**Comment by TobbeEdgeware** [comment]
Has been fixed on the vm2.dashif.org server, see Dash-Industry-Forum/dash-live-source-simulator#45.
