### ISSUE TITLE
Test Assets website not working

### ISSUE THREAD

**Issue by hapatrick** [Dash-Industry-Forum/Test-Vectors#54]
When I access the webpage at http://testassets.dashif.org/, I get a "Disclaimer" dialog. When I click the "I agree" button, I get a pop-up notice "An Error Occurred." If I then reload the webpage, I get a spinning "loading" icon. I'm not able to access any of the test data that I assume is hosted somewhere on this site...

**Comment by dsilhavy** [comment]
@hapatrick I saw you already closed the issue, can you maybe shortly explain what was causing the problem. Thanks Daniel

**Comment by hapatrick** [comment]
It seems the problem is specific to my company's network. When I'm on that network, the site doesn't work. Since then I've tried it on two other networks (same computer, same browser) and it works fine. So our corporate IT is blocking or interfering with something that prevents the site from loading, although I have no idea what.
