### ISSUE TITLE
Content protection descriptor in negative test cases

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Test-Vectors#56]
The ContentProtection descriptors shall always be present in the AdaptationSet element and apply to all contained Representations. This rule is violated among two test vectors-
http://dash.akamaized.net/dash264/TestCasesNegative/2/1.mpd
http://dash.akamaized.net/dash264/TestCasesNegative/2/2.mpd

**Comment by waqarz** [comment]
@niteeshbhat both MPDs are correct, ContentProtection is present for all representations in an adaptation set? if this is a conformance software issue check and fix

**Comment by niteeshbhat** [comment]
Yes , it was a mpd conformance issue. 
Fixed.
