### ISSUE TITLE
Update of test vectors - Microsoft CENC

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Test-Vectors#57]
http://dash.akamaized.net/dash264/TestCases/6b/microsoft/CENC_HD_Time/CENC_HD_time_MPD.mpd
http://dash.akamaized.net/dash264/TestCases/6b/microsoft/CENC_SD_Time/CENC_SD_time_MPD.mpd

- @value attribute of ContentProtection descriptor specifying a particular DRM system shall have the DRM name and version number.
- also extension element <cenc:pssh> is expected.
- @cenc:default_KID is identified by ContentProtection descriptor with @schemeIdUri="urn:mpeg:dash:mp4protection:2011 only.

**Comment by waqarz** [comment]
These vectors have been long pulled, why is this issue still open??? These are **not** in the database!!!
