### ISSUE TITLE
Incorrect colr atom size in DRM vectors

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Test-Vectors#59]
e.g. https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd

colr atom has a size of 18 bytes (Section 12.1.5.2 of ISO/IEC 14496-12 5th ed), but the media data shows 19 bytes

**Comment by sandersaares** [comment]
I count 19 as the correct size.

4 box length
4 box type
4 colour_type

Then from colour_type == nclx relation we get:
2 colour_primaries
2 transfer_characteristics
2 matrix_coefficients
1 full_range_flag+reserved

For a total of 19.

**Comment by waqarz** [comment]
I don't understand, why is colr atom mandated to have a size of 18 bytes in Section 12.1.5.2 of ISO/IEC 14496-12 5th ed?

**Comment by sandersaares** [comment]
I do not see any mention of 18 bytes in section 12.1.5.2. What exactly is the statement you refer to?

I am looking at `ISO/IEC 14496-12:2015(E)` page 159.

**Comment by waqarz** [comment]
Sorry, you seem to be correct and this is a bug with conformance software: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/210 , hope to fix it soon. Thanks again for correcting.
