### ISSUE TITLE
Test vectors provided for download

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Test-Vectors#6]
can we provide the test vectors (MPD+ segment) files, for download?

**Comment by waqarz** [comment]
The solution approach that seems ideal is to allow indexing of the data, and this is what we are working on.

**Comment by wilaw** [comment]
Indexing, which will facilitate automated download,  is now available. See 

http://dash.edgesuite.net/dash264/ 

Cheers

Will
