### ISSUE TITLE
[TTML] Language code in the application is incorrect

### ISSUE THREAD

**Issue by gitAmol** [Dash-Industry-Forum/Test-Vectors#61]
**Summary:** While testing the TTML subtitle display, we observed that for the below mpd file. The language code used for the German subtitle is not correct.
**mpd:** http://dash.edgesuite.net/dash264/TestCases/4b/qualcomm/1/ED_OnDemand_5SecSeg_Subtitles.mpd

**Details:**
We observed that in the mpd file for German language code "ge" is used as below
 
      <AdaptationSet mimeType="application/ttml+xml" lang="ge">
      <Role schemeIdUri="urn:mpeg:dash:role" value="subtitle" />
      <Representation id="8"  bandwidth="268" >
 
But "ge" is not a valid language ISO code. Refer the below link for ISO codes:

https://www.w3schools.com/tags/ref_language_codes.asp  
or, https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes 
 
For German language "de" is the valid code. App engineer has to fix this.

**Comment by waqarz** [comment]
@eceozturk please fix this, its very simple

**Comment by eceozturk** [comment]
The language code issue is fixed now ("ge" to "de") for test vectors:
http://dash.edgesuite.net/dash264/TestCases/4b/qualcomm/1/ED_OnDemand_5SecSeg_Subtitles.mpd
http://dash.edgesuite.net/dash264/TestCases/4b/qualcomm/2/TearsOfSteel_onDem5secSegSubTitles.mpd
