### ISSUE TITLE
BaseURL issue with "User cases for multiple periods" feature

### ISSUE THREAD

**Issue by bilboed** [Dash-Industry-Forum/Test-Vectors#62]
The various mpd from here have got a wrong BaseURL : http://testassets.dashif.org/#feature/details/58875da17459f8cb201b860f

` <BaseURL> http://dash.akamaized.net/dash264/TestCasesIOP33/Content </BaseURL>`

Excluding issue with trailing/leading spaces (which might introduce some confusion in some parsers), the major issue is that the BaseURL does not end with a '/', therefore according to RFC 3986 using that URL as a base URL will result in full url of type:
`http://dash.akamaized.net/dash264/TestCasesIOP33/<something>` and not `http://dash.akamaized.net/dash264/TestCasesIOP33/Content/<something>`

The logic for joining two urls is specified in RFC3986 5.2.3 https://datatracker.ietf.org/doc/html/rfc3986#section-5.2.3 :
`return a string consisting of the reference's path component
      appended to all but the last segment of the base URI's path (i.e.,
      excluding any characters after the right-most "/" in the base URI
      path, or excluding the entire base URI path if it does not contain
      any "/" characters).`

**Comment by AdithyanIlangovan** [comment]
@bilboed Thanks for pointing this out. 
Yes, some of the test vectors do not end with a '/' for the BaseURL. 
I have fixed this for now. 
To avoid confusion, I also removed the trailing/leading spaces.
I am closing this issue now.
If you still see issues, feel free to open it.
