### ISSUE TITLE
Timing Issues in several Multiple Periods Test Vectors (e.g. Test Vector 18)

### ISSUE THREAD

**Issue by sruditsky** [Dash-Industry-Forum/Test-Vectors#64]
There are several test vectors which combine a period of 250 sec of BBB, then 2 periods of ED of 60 and 50 sec and then another period of BBB of 344 sec. The periods are set in the way that the 4th period is an immediate continuation of the 1st.

I believe there are some timing issues in these test vectors:

1) The period with id="3" video has @presentationTimeOffset="3073024" which is precisely 250 sec from the beginning of BBB -- (3073024 - 1024)/12288 = 250.
However,  the audio has @presentationTimeOffset="11964416", which is 11964416/48000 = 249.26 sec from the beginning of BBB.

The result is lip-sync problems in this period.

In addition @startNumber for the audio representation of this period should be 128, (not 126).

2) In the period with id="2" video representations have @presentationTimeOffset="1024", but it should be  12288 * 60 + 1024 = 738304
Likewise the audio representation should have @presentationTimeOffset="2880000" (48000*60)

**Comment by waqarz** [comment]
@niteeshbhat  Please check this

**Comment by niteeshbhat** [comment]
Test vectors are updated as per this issue.
PTO for audio reps are corrected now.
Also video and audio PTO and startnumber updated accordingly for xlink periods.

The test vectors updated are 
http://dash.akamaized.net/dash264/TestCases/5a/nomor/1.mpd
http://dash.akamaized.net/dash264/TestCases/5a/nomor/3.mpd
http://dash.akamaized.net/dash264/TestCases/5a/nomor/4.mpd
http://dash.akamaized.net/dash264/TestCases/5a/nomor/5.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/1.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/10.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/11.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/2.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/3.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/4.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/5.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/6.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/7.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/8.mpd
http://dash.akamaized.net/dash264/TestCases/5b/nomor/9.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1a.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1b.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1c.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1d.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1e.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1f.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/5_1a.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/5_1b.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/5_1c.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/5_1d.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/5_1e.mpd
http://dash.akamaized.net/dash264/TestCases/5c/nomor/5_1f.mpd

**Comment by niteeshbhat** [comment]
The dash js does not play 2nd period mentioned in the xlink periods. 
for example http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1c.mpd

Tested with IE as chrome doesnt support here.

**Comment by niteeshbhat** [comment]
This particular issue is fixed. So closing here.
The playback problem for 2nd period of xlink is discussed as a new issue here: #86
