### ISSUE TITLE
Reference player location need to be updated

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Test-Vectors#65]
Each vector has a "play" link which points at 

http://dashif.org/reference/players/javascript/latest/samples/dash-if-reference-player/index.html?mpd=...

This needs to be updated to point at the new location of the reference player, which is now

http://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=...

Note that this new location allows the player to be loaded under both http and https. Https is necessary for the correct loading of any vectors which are themselves loaded under https and also for correct functioning of any vectors which invoke EME

**Comment by waqarz** [comment]
Implemented here: https://github.com/Dash-Industry-Forum/Test-Assets-UI/issues/30
