### ISSUE TITLE
HEVC vectors 1 & 2 don't define initialization range for video representations

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/Test-Vectors#66]
This is an issue with the first two HEVC test vectors:

http://dash.akamaized.net/dash264/TestCasesHEVC/1a/1/TOS_OnDemand_HEVC_MultiRate.mpd
http://dash.akamaized.net/dash264/TestCasesHEVC/1a/2/BBB_OnDemand_HEVC_MultiRate.mpd

For the video representations only, the SegmentBase element does not contain an `<Initialization range="xxx-yyy"/>` element to tell the client where the init data is located. Note that test vector 3 does include this information:

http://dash.akamaized.net/dash264/TestCasesHEVC/1a/9/tos_ondemand_multirate_hvc.mpd

These test vectors _might_ be technically spec compliant, but no sensible DASH streaming provider is going to omit the Initialization elements, particularly given it's trivial to include them. Please could they be added?

**Comment by waqarz** [comment]
@ojw28 this is more a question for DASH-IF IOP, I have reported it here: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/154

**Comment by waqarz** [comment]
Resolved in IOP
