### ISSUE TITLE
bitstreamswitching issue

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Test-Vectors#67]
Follwoing HEVC test vectors are using bitstreamswitching, some have different video resolutions; recommend to remove the switching flag as its not required. Related to IOP issue: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/156

  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="eng" subsegmentStartsWithSAP="1" contentType="video">
./TestCasesHEVC/1a/1/TOS_OnDemand_HEVC_MultiRate.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="und" subsegmentStartsWithSAP="1">
./TestCasesHEVC/1a/2/BBB_OnDemand_HEVC_MultiRate.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24" par="16:9" lang="eng" subsegmentStartsWithSAP="1" contentType="video">
./TestCasesHEVC/2a/1/TOS_OnDemand_HEVC_MultiRes.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24" par="16:9" lang="und" subsegmentStartsWithSAP="1">
./TestCasesHEVC/2a/2/BBB_OnDemand_HEVC_MultiRes.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="eng" contentType="video">
./TestCasesHEVC/1b/1/TOS_Live_HEVC_MultiRate.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="und">
./TestCasesHEVC/1b/2/BBB_Live_HEVC_MultiRate.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24" par="16:9" lang="eng" contentType="video">
./TestCasesHEVC/2b/1/TOS_Live_HEVC_MultiRes.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="1080" maxFrameRate="24" par="16:9" lang="und">
./TestCasesHEVC/2b/2/BBB_Live_HEVC_MultiRes.mpd
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="eng" subsegmentStartsWithSAP="1" contentType="video">
./TestCasesIOP33/MPDChaining/regular_chain/2/manifest_regular_MPDChaining_OnDemand.mpd
    <AdaptationSet id="1" group="1" profiles="ccff" bitstreamSwitching="true" segmentAlignment="true" contentType="video" mimeType="video/mp4" codecs="avc1.4D4020" maxWidth="1280" maxHeight="720" startWithSAP="1">
    <AdaptationSet id="2" group="5" profiles="ccff" bitstreamSwitching="true" segmentAlignment="true" contentType="audio" mimeType="audio/mp4" codecs="mp4a.40.2">
./TestCases/6b/microsoft/CENC_SD_Time/CENC_SD_time_MPD.mpd
                <AdaptationSet id="1" group="1" profiles="ccff" bitstreamSwitching="true" segmentAlignment="true" contentType="video" mimeType="video/mp4" codecs="avc1.640028" maxWidth="1920" maxHeight="1080" startWithSAP="1">
                <AdaptationSet id="2" group="5" profiles="ccff" bitstreamSwitching="true" segmentAlignment="true" contentType="audio" mimeType="audio/mp4" codecs="mp4a.40.2">
./TestCases/6b/microsoft/CENC_HD_Time/CENC_HD_time_MPD.mpd

**Comment by waqarz** [comment]
@eceozturk please remove the bitstreamswitching flags in the above MPDs

**Comment by eceozturk** [comment]
@bitstreamSwitching attribute is removed from the given MPDs.
