### ISSUE TITLE
mpd's with <1s offset between presenationtime and the mediatime converted to presentationtime do not start playback

### ISSUE THREAD

**Issue by kirkshoop** [Dash-Industry-Forum/Test-Vectors#7]
from: https://github.com/MSOpenTech/dash.js/issues/3

MPD’s -
http://dash.edgesuite.net/dash264/TestCasesHD/1a/qualcomm/1/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/1a/qualcomm/2/MultiRate.mpd
http://dash.edgesuite.net/dash264/TestCasesHD/2a/qualcomm/2/MultiRes.mpd

Mikhail:
The period start time for thes mpd is 0, so the player starts requesting fragments for time 0, but I see that the first segment here starts at t/timeScale = 1024 / 12228 = 0.0837. That is why video is not loaded. For audio start time is 0, so it is loaded.
 I think that these mpd's should provide presentationTimeOffset to correct the time difference. For example I have found a similar case for this mpd: http://dash.edgesuite.net/dash264/TestCases/1c/envivio/manifest.mpd. 
 Here start time of the first segment for audio and video is not 0, but the mpd has presentationTimeOffset. For audio this offset is exactly the same as a media offset, so audio is loaded, but presentationTimeOffset for video is a bit less than media offset, so video is not loaded.

Kirk:
Either mpd's are not valid because they do not provide presentationTimeOffset, or the dash.js player has to do some hack to jumpstart playback for these cases. Which is it?

**Comment by waqarz** [comment]
Hi,

This shouldn't be an issue since these representations that you have mentioned contain an edit list box ('elst') that maps media time 1024 ticks (0.08333 sec on a timescale of 12288 ticks/sec) to zero presentation time. An offset in the MPD is not needed in this case. Please reopen this issue if this doesn't address the issue.
