### ISSUE TITLE
Test vectors for thumbnail trick mode

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#73]

**Comment by eceozturk** [comment]
There are available test vectors for on-demand but live ones should be done.

**Comment by waqarz** [comment]
@niteeshbhat  Why is this not progressing? this should have been closed some time ago as we already have support for this in live emulator.

**Comment by niteeshbhat** [comment]
Ece Oeztuerk : 
I did not know that this was already supported in the live simulator. Apparently the PR is merged 11 days ago (https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/55).

**Comment by niteeshbhat** [comment]
Conformance supported and tested for test vector available in live-emulator.

conformance PRs are
https://github.com/Dash-Industry-Forum/Conformance-Software/pull/337
https://github.com/Dash-Industry-Forum/Conformance-Software/pull/336
