### ISSUE TITLE
Test vectors for external representation index for On-Demand content

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#76]
Updating test vectors to support external Representation Index for On-Demand content is needed.

**Comment by eceozturk** [comment]
Clarification is needed for this feature extension. Related issue: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/171

**Comment by waqarz** [comment]
Solved here: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/171
