### ISSUE TITLE
Test vectors for early terminated period

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#79]
Updating test vectors for early terminated period is needed.

**Comment by eceozturk** [comment]
Provided: http://testassets.dashif.org/#testcase/details/586fb3879ae9045678eab63e

**Comment by niteeshbhat** [comment]
	Feature had already been implemented in live emulator
	Vector made available under http://testassets.dashif.org/#testcase/details/586fb3879ae9045678eab63e 
	How to make segments “unavailable” in live emulator

**Comment by waqarz** [comment]
Provided: https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/28
