### ISSUE TITLE
Missing explicit reference to Creative Commons license?

### ISSUE THREAD

**Issue by dantallis-edt** [Dash-Industry-Forum/Test-Vectors#8]
I can't see/find any reference to license for the test vectors.  The indemnification click-through is clear but doesn't mention Creative Commons Attribution 4.0 International License.

**Comment by waqarz** [comment]
This is indeed an important issue, but its not just one licence that applies to all, different content may have different license. One way would be to provide license with each test vector. Isn't there another, more manageable alternate?

**Comment by haudiobe** [comment]
Waqar,

I would expect that you just add a licence footnote to each of them.

Thomas

On 12 Mar 2014, at 07:56, waqarz notifications@github.com wrote:

> This is indeed an important issue, but its not just one licence that applies to all, different content may have different license. One way would be to provide license with each test vector. Isn't there another, more manageable alternate?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Dr. Thomas Stockhammer (CEO) || stockhammer@nomor.de || phone +49 89 978980 02 || cell +491725702667 || http://www.nomor-research.com
Nomor Research GmbH  -  Sitz der Gesellschaft: München - Registergericht: München, HRB 165856 – Umsatzsteuer-ID: DE238047637 - Geschäftsführer: Dr. Thomas Stockhammer, Dr. Ingo Viering.

**Comment by waqarz** [comment]
New agreed disclaimer in place at: http://dashif.org/testvectors/
