### ISSUE TITLE
Test vectors for trick modes in live services

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#80]
Updating test vectors for trick modes in live services is needed.

**Comment by niteeshbhat** [comment]
	Basic implementation to support this added to live emulator: https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/52
	Need IDR-only representation

**Comment by waqarz** [comment]
Pending clarification in IOP: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/172
