### ISSUE TITLE
Sample asset has invalid HTTPS headers.

### ISSUE THREAD

**Issue by theodab** [Dash-Industry-Forum/Test-Vectors#85]
For the [Shaka Player demo page](https://shaka-player-demo.appspot.com/demo/#asset=//dash.edgesuite.net/dash264/TestCases/1c/qualcomm/2/MultiRate.mpd;lang=en-US;build=uncompiled), we use a number of public domain assets as example assets, including your dash-if assets. One of them, the copy of Big Buck Bunny located at [this URL](https://dash.edgesuite.net/dash264/TestCases/1c/qualcomm/2/MultiRate.mpd), seems to have a problem with its HTTPS headers. If you try to download it in Chrome, there is an `ERR_CERT_COMMON_NAME_INVALID` error. Similarly, Safari puts an error about the certificate being invalid into the dev console.

@wilaw, is this the right place to put this issue?
@joeyparrish

**Comment by niteeshbhat** [comment]
All vectors listed in dash test assets webpage: http://testassets.dashif.org/#testvector/list has been updated to domain dash.akamaized.net. It supports http and https.

You can update the links in your webpage to point to the new domain (dash.akamaized.net).

**Comment by theodab** [comment]
Thanks for the help!
