### ISSUE TITLE
Not able to play 2nd period of xlink periods

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Test-Vectors#86]
The dash js does not play 2nd period mentioned in the xlink periods. 
for example http://dash.akamaized.net/dash264/TestCases/5c/nomor/4_1c.mpd
and other vectors in /TestCases/5a, 5b/ and 5c/

Tested with IE as chrome doesnt support here.

**Comment by waqarz** [comment]
If the content is conforming, we open an issue with dash.js and close it here

**Comment by niteeshbhat** [comment]
Yes, the content is conforming. 
Closing here. I will open an issue in dash js.
