### ISSUE TITLE
Naming of test vectors have issues

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Test-Vectors#87]
Propose a way to make dash.js list more informative

- Duplicate names
- Non instructive information in names

**Comment by waqarz** [comment]
What we have today in database is extremely confusing: we have a field names "Test Vector", some time it has a numerical identifier (Test Vector 1, 2) and some time its a name.

Lets open an important issue and fix this in the database: We need to have two fields each for a test case and test vector:

1. *identifier* : this is a simple numerical string: e.g. Test Case 1, 2, 3..., Test Vector 1, 2, 3,.... There can be discontinuities in the list but *no overlap or repetition* e.g. repeated test vector identifier.
2. *Name* : This is a short, 4 - 5 word name of each test case and test vector that tries to give some meaningful name to the test case and test vector.

For this you need to create new attribute of name if does not exist (make it public) and rename the Test Vector field to Identifier... we need a major cleanup here.

**Comment by eceozturk** [comment]
Both test vectors and test cases are assigned a meaningful name and an identifier.
