### ISSUE TITLE
Issue with subtitle content

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Test-Vectors#95]
https://github.com/Dash-Industry-Forum/dash.js/issues/2789

**Comment by niteeshbhat** [comment]
There were multiple issues with the subtitles under test case 'TestCases/4b/qualcomm'.
All issues resolved now and deployed.
Subtitles conformance passes on the validator here - https://subcheck.io/#/

The list of errors are listed here for future reference.
1. http://dash.akamaized.net/dash264/TestCases/4b/qualcomm/2/TearsOfSteel_onDem5secSegSubTitles.mpd   -  German character encoding error
2. http://dash.akamaized.net/dash264/TestCases/4b/qualcomm/1/ED_OnDemand_5SecSeg_Subtitles.mpd
- tts:extent element signalling was missing, 
- begin time stamp was not conforming,
- IMSC profile missing,
- allow origin header missing (to play the content in https)
3. http://dash.akamaized.net/dash264/TestCases/4b/qualcomm/3/Solekai.mpd
- framerate signalling missing at the root element.
