### ISSUE TITLE
Test vectors for multi-track compatible signaling

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#97]
Here some recommendations implemented (codec/bit depth), other recommendations need to be implemented for test vector support.

**Comment by niteeshbhat** [comment]
Audio language alternate content provided here
https://dash.akamaized.net/dash264/TestCasesIOP41/MultiTrack/alternative_content/6/manifest_alternative_lang.mpd

Other recommendations supported - Essentialproperty, MaxWidth
, all test vectors can be found here
https://testassets.dashif.org/#testcase/details/5a1c4c8f7cccbb15567e5682
