### ISSUE TITLE
Support program Events

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#98]
Support program Events such as source audio language or format change, resolution or format of video content change, codecs or profiles or level change, number of representation change. For simple live and main live cases (IOP 4.2 section 4.11 Deployment scenarios).

**Comment by niteeshbhat** [comment]
This is not exactly a requirement. 
The program events 'emsg', including scte35 cues are already supported  in live emulator / live test vectors.
So the above issue seems more like redundant additions (?). 
More guidelines/decision expected.

**Comment by waqarz** [comment]
There are no specific feature requests here. Various individual features related to this are already available in live sim
