### ISSUE TITLE
Simple live scenario

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Test-Vectors#99]
In case of simple live- When next segment generation is not possible, generate new MPD as in 4.11.4: By doing so, the content provider basically informs the DASH client that for the duration of the Segment as announced, no media is available. The DASH client revalidates this after every Segment duration. The MPD is not changed on the server until either the decoder resumes or the Media Presentation is terminated. Later when segments are generated, a new MPD is written again with parameters as in 4.11.4.

**Comment by niteeshbhat** [comment]
By checking back in IOP, found in section 4.11.3.5, that the segment loss in the case of simple-live profile is through early teminated periods. An implementation has been already done for 'early terminated periods' (https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/28).
